r3almX_backend\chat_service\channel_system\channel_utils.py:65: error: Argument 2 to "get_dynamic_model" has incompatible type "list[object]"; expected "list[Column[Any]]"  [arg-type]
r3almX_backend\chat_service\channel_system\channel_utils.py:77: error: Argument 2 to "get_dynamic_model" has incompatible type "list[object]"; expected "list[Column[Any]]"  [arg-type]
r3almX_backend\chat_service\channel_system\channel_utils.py:98: error: Incompatible return value type (got "uuid.UUID", expected "sqlalchemy.sql.sqltypes.UUID[Any]")  [return-value]
r3almX_backend\chat_service\channel_system\channel_utils.py:119: error: Incompatible return value type (got "uuid.UUID", expected "sqlalchemy.sql.sqltypes.UUID[Any]")  [return-value]
r3almx_backend\chat_service\channel_system\channel_utils.py:65: error: Argument 2 to "get_dynamic_model" has incompatible type "list[object]"; expected "list[Column[Any]]"  [arg-type]
r3almx_backend\chat_service\channel_system\channel_utils.py:77: error: Argument 2 to "get_dynamic_model" has incompatible type "list[object]"; expected "list[Column[Any]]"  [arg-type]
r3almx_backend\chat_service\channel_system\channel_utils.py:98: error: Incompatible return value type (got "uuid.UUID", expected "sqlalchemy.sql.sqltypes.UUID[Any]")  [return-value]
r3almx_backend\chat_service\channel_system\channel_utils.py:119: error: Incompatible return value type (got "uuid.UUID", expected "sqlalchemy.sql.sqltypes.UUID[Any]")  [return-value]
r3almX_backend\realtime_service\DigestionBroker.py:16: error: Need type annotation for "message_batch" (hint: "message_batch: List[<type>] = ...")  [var-annotated]
r3almX_backend\realtime_service\DigestionBroker.py:100: error: Item "None" of "AsyncSession | None" has no attribute "execute"  [union-attr]
r3almX_backend\realtime_service\DigestionBroker.py:103: error: Item "None" of "AsyncSession | None" has no attribute "commit"  [union-attr]
r3almX_backend\realtime_service\DigestionBroker.py:108: error: Item "None" of "AsyncSession | None" has no attribute "rollback"  [union-attr]
r3almx_backend\realtime_service\DigestionBroker.py:16: error: Need type annotation for "message_batch" (hint: "message_batch: List[<type>] = ...")  [var-annotated]
r3almx_backend\realtime_service\DigestionBroker.py:100: error: Item "None" of "AsyncSession | None" has no attribute "execute"  [union-attr]
r3almx_backend\realtime_service\DigestionBroker.py:103: error: Item "None" of "AsyncSession | None" has no attribute "commit"  [union-attr]
r3almx_backend\realtime_service\DigestionBroker.py:108: error: Item "None" of "AsyncSession | None" has no attribute "rollback"  [union-attr]
r3almX_backend\auth_service\user_handler_utils.py:17: error: Argument 1 to "filter" of "Select" has incompatible type "bool | ColumnElement[bool]"; expected "ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
r3almX_backend\auth_service\user_handler_utils.py:22: error: Argument 1 to "filter" of "Select" has incompatible type "bool | ColumnElement[bool]"; expected "ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
r3almX_backend\auth_service\user_handler_utils.py:23: error: Incompatible return value type (got "User | None", expected "User")  [return-value]
r3almX_backend\auth_service\user_handler_utils.py:27: error: Argument 1 to "filter" of "Select" has incompatible type "bool | ColumnElement[bool]"; expected "ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
r3almX_backend\auth_service\user_handler_utils.py:28: error: Incompatible return value type (got "User | None", expected "User")  [return-value]
r3almx_backend\auth_service\user_handler_utils.py:17: error: Argument 1 to "filter" of "Select" has incompatible type "bool | ColumnElement[bool]"; expected "ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
r3almx_backend\auth_service\user_handler_utils.py:22: error: Argument 1 to "filter" of "Select" has incompatible type "bool | ColumnElement[bool]"; expected "ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
r3almx_backend\auth_service\user_handler_utils.py:23: error: Incompatible return value type (got "User | None", expected "User")  [return-value]
r3almx_backend\auth_service\user_handler_utils.py:27: error: Argument 1 to "filter" of "Select" has incompatible type "bool | ColumnElement[bool]"; expected "ColumnElement[bool] | _HasClauseElement[bool] | SQLCoreOperations[bool] | ExpressionElementRole[bool] | TypedColumnsClauseRole[bool] | Callable[[], ColumnElement[bool]] | LambdaElement"  [arg-type]
r3almx_backend\auth_service\user_handler_utils.py:28: error: Incompatible return value type (got "User | None", expected "User")  [return-value]
r3almX_backend\auth_service\auth_utils.py:115: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almX_backend\auth_service\auth_utils.py:121: error: Argument "email" to "get_user_by_email" has incompatible type "str | None"; expected "str"  [arg-type]
r3almx_backend\auth_service\auth_utils.py:115: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almx_backend\auth_service\auth_utils.py:121: error: Argument "email" to "get_user_by_email" has incompatible type "str | None"; expected "str"  [arg-type]
r3almX_backend\realtime_service\chat_service.py:57: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almX_backend\realtime_service\chat_service.py:268: error: Cannot determine type of "realtime"  [has-type]
r3almX_backend\realtime_service\chat_service.py:282: error: Cannot determine type of "realtime"  [has-type]
r3almX_backend\realtime_service\connection_service.py:21: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almX_backend\realtime_service\connection_service.py:25: error: Incompatible return value type (got "JWTError", expected "User")  [return-value]
r3almX_backend\realtime_service\connection_service.py:53: error: Missing positional argument "key" in call to "hget" of "HashCommands"  [call-arg]
r3almX_backend\realtime_service\connection_service.py:54: error: Item "str" of "str | None" has no attribute "value"  [union-attr]
r3almX_backend\realtime_service\connection_service.py:54: error: Item "None" of "str | None" has no attribute "value"  [union-attr]
r3almX_backend\realtime_service\connection_service.py:94: error: "Connection" has no attribute "connection_cache_list"  [attr-defined]
r3almX_backend\realtime_service\connection_service.py:112: error: Cannot determine type of "realtime"  [has-type]
r3almX_backend\realtime_service\connection_service.py:119: error: Cannot determine type of "realtime"  [has-type]
r3almX_backend\realtime_service\connection_service.py:126: error: Cannot determine type of "realtime"  [has-type]
r3almX_backend\realtime_service\main.py:6: error: Name "redis" already defined (by an import)  [no-redef]
r3almX_backend\auth_service\auth_routes.py:29: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:92: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:126: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:150: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almX_backend\auth_service\auth_routes.py:166: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:202: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:234: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:264: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\auth_service\auth_routes.py:314: error: Cannot determine type of "auth_router"  [has-type]
r3almX_backend\chat_service\room_service\room_management_endpoints.py:24: error: Cannot determine type of "rooms_service"  [has-type]
r3almX_backend\chat_service\room_service\room_management_endpoints.py:48: error: Cannot determine type of "rooms_service"  [has-type]
r3almX_backend\chat_service\room_service\room_management_endpoints.py:54: error: Cannot determine type of "rooms_service"  [has-type]
r3almX_backend\chat_service\room_service\room_management_endpoints.py:60: error: Cannot determine type of "rooms_service"  [has-type]
r3almX_backend\chat_service\room_service\room_management_endpoints.py:77: error: Cannot determine type of "rooms_service"  [has-type]
r3almX_backend\chat_service\room_service\room_management_endpoints.py:98: error: Cannot determine type of "rooms_service"  [has-type]
r3almX_backend\chat_service\invite_system\invite_system_endpoint.py:18: error: Cannot determine type of "invite_system"  [has-type]
r3almX_backend\chat_service\invite_system\invite_system_endpoint.py:50: error: Cannot determine type of "invite_system"  [has-type]
r3almX_backend\chat_service\invite_system\invite_system_endpoint.py:95: error: Cannot determine type of "invite_system"  [has-type]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:33: error: Cannot determine type of "channel_manager"  [has-type]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:55: error: Cannot determine type of "channel_manager"  [has-type]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:70: error: Name "create_channel" already defined on line 33  [no-redef]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:70: error: Cannot determine type of "channel_manager"  [has-type]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:79: error: Value of type "Coroutine[Any, Any, UUID[Any]]" must be used  [unused-coroutine]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:79: note: Are you missing an await?
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:92: error: Cannot determine type of "channel_manager"  [has-type]
r3almX_backend\chat_service\channel_system\channel_management_endpoints.py:138: error: Name "delete_channel" already defined on line 98  [no-redef]
r3almx_backend\auth_service\auth_routes.py:22: error: Incompatible import of "UsersConfig" (imported name has type "type[r3almx_backend.auth_service.Config.UsersConfig]", local name has type "type[r3almX_backend.auth_service.Config.UsersConfig]")  [assignment]
r3almx_backend\auth_service\auth_routes.py:150: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almX_backend\inst_modifiers.py:8: error: Cannot determine type of "r3almX"  [has-type]
r3almX_backend\inst_modifiers.py:16: error: Name "logger" is not defined  [name-defined]
r3almX_backend\friends_service\friends_endpoint.py:34: error: Item "ColumnElement[Any]" of "list[str] | ColumnElement[Any]" has no attribute "__iter__" (not iterable)  [union-attr]
r3almX_backend\friends_service\friends_endpoint.py:61: error: No overload variant of "__and__" of "bool" matches argument type "ColumnElement[bool]"  [operator]
r3almX_backend\friends_service\friends_endpoint.py:61: note: Possible overload variants:
r3almX_backend\friends_service\friends_endpoint.py:61: note:     def __and__(self, bool, /) -> bool
r3almX_backend\friends_service\friends_endpoint.py:61: note:     def __and__(self, int, /) -> int
r3almX_backend\friends_service\friends_endpoint.py:61: note: Both left and right operands are unions
r3almX_backend\friends_service\friends_endpoint.py:61: error: Item "list[str]" of "list[str] | Column[NoReturn]" has no attribute "contains"  [union-attr]
r3almx_backend\realtime_service\connection_service.py:21: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almx_backend\realtime_service\connection_service.py:25: error: Incompatible return value type (got "JWTError", expected "User")  [return-value]
r3almx_backend\realtime_service\connection_service.py:53: error: Missing positional argument "key" in call to "hget" of "HashCommands"  [call-arg]
r3almx_backend\realtime_service\connection_service.py:54: error: Item "str" of "str | None" has no attribute "value"  [union-attr]
r3almx_backend\realtime_service\connection_service.py:54: error: Item "None" of "str | None" has no attribute "value"  [union-attr]
r3almx_backend\realtime_service\connection_service.py:94: error: "Connection" has no attribute "connection_cache_list"  [attr-defined]
r3almx_backend\realtime_service\chat_service.py:57: error: Incompatible types in assignment (expression has type "Any | None", variable has type "str")  [assignment]
r3almx_backend\chat_service\channel_system\channel_management_endpoints.py:70: error: Name "create_channel" already defined on line 33  [no-redef]
r3almx_backend\chat_service\channel_system\channel_management_endpoints.py:79: error: Value of type "Coroutine[Any, Any, UUID[Any]]" must be used  [unused-coroutine]
r3almx_backend\chat_service\channel_system\channel_management_endpoints.py:79: note: Are you missing an await?
r3almx_backend\chat_service\channel_system\channel_management_endpoints.py:138: error: Name "delete_channel" already defined on line 98  [no-redef]
r3almx_backend\proj_logger.py:9: error: Name "logger" already defined (by an import)  [no-redef]
r3almx_backend\proj_logger.py:23: error: Incompatible types in assignment (expression has type "Logger", variable has type Module)  [assignment]
r3almx_backend\proj_logger.py:24: error: Module has no attribute "setLevel"  [attr-defined]
r3almx_backend\proj_logger.py:35: error: Item "None" of "Address | None" has no attribute "host"  [union-attr]
r3almx_backend\inst_modifiers.py:16: error: Name "logger" is not defined  [name-defined]
r3almx_backend\realtime_service\main.py:6: error: Name "redis" already defined (by an import)  [no-redef]
r3almx_backend\realtime_service\main.py:6: error: Incompatible import of "NotificationSystem" (imported name has type "type[r3almx_backend.realtime_service.connection_service.NotificationSystem]", local name has type "type[r3almX_backend.realtime_service.connection_service.NotificationSystem]")  [assignment]
r3almx_backend\realtime_service\main.py:6: error: Incompatible import of "notification_system" (imported name has type "r3almx_backend.realtime_service.connection_service.NotificationSystem", local name has type "r3almX_backend.realtime_service.connection_service.NotificationSystem")  [assignment]
r3almx_backend\friends_service\friends_endpoint.py:34: error: Item "ColumnElement[Any]" of "list[str] | ColumnElement[Any]" has no attribute "__iter__" (not iterable)  [union-attr]
r3almx_backend\friends_service\friends_endpoint.py:61: error: No overload variant of "__and__" of "bool" matches argument type "ColumnElement[bool]"  [operator]
r3almx_backend\friends_service\friends_endpoint.py:61: note: Possible overload variants:
r3almx_backend\friends_service\friends_endpoint.py:61: note:     def __and__(self, bool, /) -> bool
r3almx_backend\friends_service\friends_endpoint.py:61: note:     def __and__(self, int, /) -> int
r3almx_backend\friends_service\friends_endpoint.py:61: note: Both left and right operands are unions
r3almx_backend\friends_service\friends_endpoint.py:61: error: Item "list[str]" of "list[str] | Column[NoReturn]" has no attribute "contains"  [union-attr]
Found 96 errors in 25 files (checked 46 source files)
